-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 13, 2023 at 08:09 AM
-- Server version: 10.5.20-MariaDB
-- PHP Version: 7.3.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `id20966934_pokebuy`
--

-- --------------------------------------------------------

--
-- Table structure for table `pokemons`
--

CREATE TABLE `pokemons` (
  `id` int(10) NOT NULL,
  `name` varchar(50) NOT NULL,
  `image` varchar(300) NOT NULL,
  `description` varchar(500) NOT NULL,
  `atk` int(11) NOT NULL,
  `hp` int(11) NOT NULL,
  `def` int(11) NOT NULL,
  `sp_atk` int(11) NOT NULL,
  `sp_def` int(11) NOT NULL,
  `spd` int(11) NOT NULL,
  `location` int(11) NOT NULL,
  `rarity` varchar(50) NOT NULL DEFAULT 'common'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `pokemons`
--

INSERT INTO `pokemons` (`id`, `name`, `image`, `description`, `atk`, `hp`, `def`, `sp_atk`, `sp_def`, `spd`, `location`, `rarity`) VALUES
(1, 'Bulbasaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 'Bulbasaur is a grass and poison type Pokémon. It has a small, reptile-like body with a large plant bulb on its back. The bulb grows into a large plant as Bulbasaur evolves. It is calm and docile, but it can unleash powerful vine whip attacks when provoked.', 49, 45, 49, 65, 65, 45, 3, 'common'),
(2, 'Ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'Ivysaur is the evolved form of Bulbasaur. It has a bigger and taller body with a more developed plant bulb on its back. The plant bulb contains various nutrients that provide sustenance to Ivysaur. It is known to be a diligent Pokémon that basks in sunlight to charge up its energy.', 62, 60, 63, 80, 80, 60, 5, 'rare'),
(3, 'Venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'Venusaur is the final evolved form of Bulbasaur. It has a massive body with a fully bloomed flower on its back. The flower releases a soothing aroma that can calm people and other Pokémon. Venusaur is a protective and powerful Pokémon that uses its flower petals to whip opponents and unleash devastating solar beam attacks.', 82, 80, 83, 100, 100, 80, 4, 'epic'),
(4, 'Charmander', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'Charmander is a fire type Pokémon. It has a small dinosaur-like body with a flame burning at the tip of its tail. The flame grows bigger and brighter as Charmander evolves. It is a playful Pokémon, but its fiery nature can ignite powerful ember attacks when in battle.', 52, 39, 43, 60, 50, 65, 1, 'common'),
(5, 'Charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 'Charmeleon is the evolved form of Charmander. It has a more muscular and reptilian body with a larger flame on its tail. Charmeleon possesses a strong and independent personality. It tends to be hot-headed and fiercely protective of its territory. When provoked, Charmeleon can unleash intense flamethrower attacks to defeat its opponents.', 64, 58, 58, 80, 65, 80, 4, 'rare'),
(6, 'Charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 'Charizard is the final evolved form of Charmander. It has a majestic and powerful appearance with large wings and fiery breath. Charizard is known as the Flame Pokémon and has the ability to fly. It is an incredibly strong and proud Pokémon that is capable of burning down anything in its path with its devastating flamethrower and fire blast attacks.', 84, 78, 78, 109, 85, 100, 5, 'epic'),
(7, 'Squirtle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 'Squirtle is a water type Pokémon. It has a small and turtle-like body with a shell on its back. The shell provides excellent defense and acts as a shield. Squirtle is an excellent swimmer and can shoot powerful water gun attacks from its mouth. Despite its small size, Squirtle is known to be a determined and resilient Pokémon.', 48, 44, 65, 50, 64, 43, 3, 'common'),
(8, 'Wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 'Wartortle is the evolved form of Squirtle. It has a larger and more developed shell on its back and sharp claws for swimming at high speeds. Wartortle is a skilled Pokémon in both water and land battles. It is known to be an adept diver and can unleash powerful water-based attacks like hydro pump to defeat its opponents.', 63, 59, 80, 65, 80, 58, 5, 'rare'),
(9, 'Blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 'Blastoise is the final evolved form of Squirtle. It is a massive and powerful Pokémon with water cannons on its shell. Blastoise can shoot water projectiles with tremendous force and accuracy. It has incredibly strong defenses and is known for its resilience in battles. Blastoise is a natural leader and displays an unwavering determination to protect its territory.', 83, 79, 100, 85, 105, 78, 4, 'epic'),
(10, 'Caterpie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', 'Caterpie is a bug type Pokémon. It has a small, worm-like body covered in green and yellow stripes. Caterpie is known for its voracious appetite and can devour leaves in large quantities. Despite its size, it is a timid and non-confrontational Pokémon that relies on its string shot and tackle attacks to defend itself when threatened.', 30, 45, 35, 20, 20, 45, 5, 'common'),
(11, 'Metapod', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', 'Metapod is the evolved form of Caterpie. Its body is encased in a hard, shell-like exterior, which provides excellent protection. Metapod is often mistaken for a tree branch due to its motionless state. It is in the process of preparing for evolution, and its only move is harden, which strengthens its defense.', 20, 50, 55, 25, 25, 30, 2, 'rare'),
(12, 'Butterfree', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', 'Butterfree is the final evolved form of Caterpie. It has vibrant wings with colorful patterns that allow it to fly gracefully. Butterfree is known for its powdery scales that it releases to create mesmerizing displays and to put opponents to sleep. It is a gentle and caring Pokémon that can navigate through forests and fields with ease.', 45, 60, 50, 90, 80, 70, 4, 'epic'),
(13, 'Weedle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', 'Weedle is a bug and poison type Pokémon. It has a small, brown-colored body with a needle-like stinger on its head. Weedle is known for its acute sense of smell, which allows it to detect its favorite food - leaves. It is a cautious Pokémon that can defend itself using its poison sting attack when threatened.', 35, 40, 30, 20, 20, 50, 5, 'common'),
(14, 'Kakuna', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', 'Kakuna is the evolved form of Weedle. Its body becomes harder and more cocoon-like, providing increased protection. Kakuna remains motionless while awaiting its evolution, and it can endure harsh conditions without eating. Its only move is harden, which strengthens its defense.', 25, 45, 50, 25, 25, 35, 2, 'rare'),
(15, 'Beedrill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', 'Beedrill is the final evolved form of Weedle. It has a slender body with large wings and a sharp stinger on its tail. Beedrill is known for its aggressive nature and powerful attacks. It can unleash a barrage of stinging needles and poison jabs to incapacitate its opponents. Beedrill is a territorial Pokémon that fiercely guards its nest.', 90, 65, 40, 45, 80, 75, 3, 'epic'),
(16, 'Pidgey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', 'Pidgey is a normal and flying type Pokémon. It has a small and plump body with large wings. Pidgey is known for its excellent vision, which allows it to spot prey from great distances. It is a common sight in forests and fields, where it soars through the sky and catches insects with its sharp beak and claws.', 45, 40, 40, 35, 35, 56, 1, 'common'),
(17, 'Pidgeotto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', 'Pidgeotto is the evolved form of Pidgey. It has a larger and more powerful body with sharper talons and feathers. Pidgeotto is an agile Pokémon that can fly at high speeds and perform impressive aerial maneuvers. It hunts for prey from the skies and uses its sharp beak and talons to strike with precision and power.', 60, 63, 55, 50, 50, 71, 2, 'rare'),
(18, 'Pidgeot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', 'Pidgeot is the final evolved form of Pidgey. It has a majestic and commanding presence with its large wingspan and sharp beak. Pidgeot is an exceptional flyer and can soar through the sky at incredible speeds. It is a proud Pokémon that defends its territory fiercely and uses its powerful wings to create gusts of wind and launch devastating aerial attacks.', 80, 83, 75, 70, 70, 101, 3, 'epic'),
(19, 'Rattata', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', 'Rattata is a normal type Pokémon. It has a small and rodent-like body with large incisors. Rattata is known for its agility and quick movements, which allow it to scurry around and avoid predators. It has a strong sense of smell and can detect food from long distances. Rattata uses its sharp teeth to gnaw on anything it can find and defends itself using its tackle and bite attacks.', 56, 30, 35, 25, 35, 72, 1, 'common'),
(20, 'Raticate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png', 'Raticate is the evolved form of Rattata. It has a larger and more muscular body with powerful jaws. Raticate is a territorial Pokémon that marks its territory by gnawing on objects and leaving bite marks. It is an excellent swimmer and can navigate through water with ease. Raticate is an aggressive Pokémon that uses its sharp teeth and quick movements to launch devastating attacks on its opponents.', 81, 55, 60, 50, 70, 97, 2, 'rare'),
(21, 'Spearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png', 'Spearow is a normal and flying type Pokémon. It has a small and bird-like body with a sharp beak and talons. Spearow is known for its high-pitched cries, which can be heard from a considerable distance. It is a highly territorial Pokémon that fiercely defends its nesting grounds. Spearow can fly at high speeds and uses its beak and talons to strike with precision and ferocity.', 60, 40, 30, 31, 31, 70, 1, 'common'),
(22, 'Fearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png', 'Fearow is the evolved form of Spearow. It has a larger and more imposing body with a longer beak and sharp talons. Fearow is an agile flyer that can cover vast distances in a short amount of time. It is a fearless Pokémon that dives from the sky to attack its prey with incredible speed and power. Fearow is also known for its territorial behavior and aggressive nature.', 90, 65, 65, 61, 61, 100, 2, 'rare'),
(23, 'Ekans', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', 'Ekans is a poison type Pokémon. It has a serpentine body covered in purple scales. Ekans is known for its cunning and sneaky behavior. It moves silently through grass and strikes its prey with a swift bite. Ekans can coil its body tightly to constrict its opponents and uses its toxic fangs to deliver venomous attacks.', 60, 35, 44, 40, 54, 55, 3, 'epic'),
(24, 'Arbok', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png', 'Arbok is the evolved form of Ekans. It has a larger and more intimidating appearance with a hood-like structure on its neck. Arbok is a highly territorial Pokémon that defends its territory fiercely. It can intimidate opponents with its menacing glare and unleash powerful poison-based attacks. Arbok\'s large fangs are capable of injecting venom into its prey, incapacitating them swiftly.', 85, 60, 69, 65, 79, 80, 4, 'rare'),
(25, 'Pikachu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'Pikachu is an electric type Pokémon and the iconic mascot of the Pokémon franchise. It has a small and mouse-like body covered in yellow fur. Pikachu is known for its adorable appearance and its ability to generate electricity. It stores electrical energy in its cheeks and releases powerful electric shocks when threatened or during battles. Pikachu is a friendly and loyal Pokémon that forms strong bonds with its trainers.', 55, 35, 40, 50, 50, 90, 5, 'common'),
(26, 'Raichu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png', 'Raichu is the evolved form of Pikachu. It has a larger and more muscular body with longer ears and a more prominent tail. Raichu has an even higher electrical charge than Pikachu and can generate powerful electric currents. It can discharge electricity from its body to create brilliant and stunning displays. Raichu is a proud and confident Pokémon that excels in battles.', 90, 60, 55, 90, 80, 110, 3, 'rare'),
(27, 'Sandshrew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png', 'Sandshrew is a ground type Pokémon. It has a tough and spiky hide that provides excellent protection. Sandshrew is known for burrowing underground to avoid extreme temperatures and predators. It can roll itself into a tight ball and uses its sharp claws to defend itself from attackers. Sandshrew is commonly found in deserts and rocky terrains.', 75, 50, 85, 20, 30, 40, 4, 'common'),
(28, 'Sandslash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png', 'Sandslash is the evolved form of Sandshrew. It has a larger and more formidable body with longer claws and spikes. Sandslash is an adept digger and can create tunnels underground with ease. It uses its sharp claws to slash enemies and can curl its body into a ball to roll at high speeds. Sandslash is territorial and fiercely defends its burrows from intruders.', 100, 75, 110, 45, 55, 65, 3, 'rare'),
(29, 'Nidoran♀', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png', 'Nidoran♀ is a poison type Pokémon. It has a small and rabbit-like body with pinkish fur and a single horn on its forehead. Nidoran♀ is known for its gentle and nurturing nature. It has highly developed senses and can detect the presence of foes and other Pokémon from afar. Nidoran♀ defends itself using poison-based attacks and its sharp claws.', 47, 55, 52, 40, 40, 41, 1, 'common'),
(30, 'Nidorina', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png', 'Nidorina is the evolved form of Nidoran♀. It has a larger and more elegant body with longer ears and a horn on its forehead. Nidorina is a caring and protective Pokémon that looks after its young. It releases a sweet fragrance to communicate with other Pokémon and uses its keen senses to detect danger. Nidorina can deliver powerful strikes using its horn and claws.', 62, 70, 67, 55, 55, 56, 2, 'rare'),
(31, 'Nidoqueen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png', 'Nidoqueen is the final evolved form of Nidoran♀. It has a majestic and powerful appearance with a larger body and prominent horn. Nidoqueen is a strong and fierce Pokémon that protects its territory and young with unwavering determination. It can launch powerful ground-based attacks and has a tough hide that provides excellent defense. Nidoqueen\'s horn is capable of injecting venom into its opponents.', 92, 90, 87, 75, 85, 76, 3, 'epic'),
(32, 'Nidoran♂', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png', 'Nidoran♂ is a poison type Pokémon. It has a small and rabbit-like body with bluish fur and large ears. Nidoran♂ has prominent fangs and sharp claws. It can release toxic spines from its back when threatened. Nidoran♂ is highly territorial and fiercely protects its territory. It uses its keen senses to detect enemies and communicate with other Pokémon. Nidoran♂ is known for its aggressive and competitive nature. It engages in territorial disputes with other Pokémon, especially those of the same g', 57, 46, 40, 40, 40, 50, 5, 'common'),
(33, 'Nidorino', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png', 'Nidorino is the evolved form of Nidoran♂. It has a larger and more muscular body with a horn on its forehead. Nidorino is a strong and independent Pokémon that constantly seeks battles and challenges. It is highly competitive and always eager to prove its strength. Nidorino uses its sharp horn and powerful attacks to overpower its opponents.', 72, 61, 57, 55, 55, 65, 4, 'rare'),
(34, 'Nidoking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png', 'Nidoking is the final evolved form of Nidoran♂. It has a massive and imposing body with a large horn and powerful limbs. Nidoking is a fearsome and dominant Pokémon that reigns over its territory with brute force. It has incredible strength and can unleash devastating ground and poison-based attacks. Nidoking\'s powerful tail can level mountains and create massive fissures in the ground.', 102, 81, 77, 85, 75, 85, 5, 'epic'),
(35, 'Clefairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png', 'Clefairy is a fairy type Pokémon. It has a small and round body covered in light pink fur. Clefairy is known for its playful and mischievous nature. It is often found in moonlit areas, dancing and frolicking. Clefairy possesses the ability to manipulate the power of the moon and can create enchanting displays of light. It is a friendly and sociable Pokémon that enjoys the company of humans and other Pokémon.', 45, 70, 48, 60, 65, 35, 4, 'common'),
(36, 'Clefable', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png', 'Clefable is the evolved form of Clefairy. It has a larger and more elegant appearance with a round body and long ears. Clefable possesses an enchanting and soothing aura that can calm the emotions of those around it. It is a gentle and compassionate Pokémon that brings happiness and joy wherever it goes. Clefable can manipulate lunar energy and is known for its powerful magic-based attacks.', 70, 95, 73, 85, 90, 60, 5, 'rare'),
(37, 'Vulpix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png', 'Vulpix is a fire type Pokémon. It has a small and fox-like body covered in orange fur. Vulpix is known for its beautiful and luxurious tail, which splits into six strands as it grows older. The temperature of its body can reach extreme levels, and it uses its fiery tail to regulate its body heat. Vulpix is a loyal and intelligent Pokémon that forms strong bonds with its trainers. It is commonly found in volcanic areas and hot climates.', 41, 38, 40, 50, 65, 65, 1, 'common'),
(38, 'Ninetales', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png', 'Ninetales is the evolved form of Vulpix. It has a majestic and mystical appearance with nine long and flowing tails. Each tail contains its own unique power and can emit a hypnotic aura. Ninetales is a wise and ancient Pokémon that possesses incredible intelligence and knowledge. It can live for hundreds of years and is known for its ability to create illusions using its mystical powers.', 76, 73, 75, 81, 100, 100, 2, 'rare'),
(39, 'Jigglypuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png', 'Jigglypuff is a normal and fairy type Pokémon. It has a round and balloon-like body covered in soft, pink fur. Jigglypuff is known for its soothing and melodic voice. It loves to sing lullabies that can put anyone to sleep. However, it gets upset if its audience falls asleep before it finishes its performance. Jigglypuff is a playful and mischievous Pokémon that enjoys drawing on the faces of those who fall asleep during its singing.', 45, 115, 20, 45, 25, 20, 5, 'common'),
(40, 'Wigglytuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png', 'Wigglytuff is the evolved form of Jigglypuff. It has a larger and more round body with fluffy fur. Wigglytuff is known for its powerful lungs that can produce a wider range of melodious sounds. Its voice has a calming effect and can ease tension and stress. Wigglytuff is a caring and compassionate Pokémon that spreads happiness and joy with its music. It is commonly found in peaceful and serene environments.', 70, 140, 45, 75, 50, 45, 3, 'rare'),
(41, 'Zubat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', 'Zubat is a poison and flying type Pokémon. It has a small and bat-like body with purple skin and blue eyes. Zubat is known for its ability to navigate in complete darkness using echolocation. It emits ultrasonic waves and listens to the echoes to determine the location of objects and prey. Zubat is often found in caves and dark places where it roosts upside down. It is a stealthy and agile Pokémon that strikes its opponents with swift and accurate attacks.', 45, 40, 35, 30, 40, 55, 4, 'common'),
(42, 'Golbat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png', 'Golbat is the evolved form of Zubat. It has a larger and more menacing appearance with elongated fangs and wings. Golbat has a voracious appetite and feeds on the blood of other Pokémon and animals. It uses its sharp fangs to puncture its prey and extract blood. Golbat is highly skilled in aerial combat and can fly for long distances without rest. It is commonly found in dark caves and forests.', 80, 75, 70, 65, 75, 90, 4, 'rare'),
(43, 'Oddish', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png', 'Oddish is a grass and poison type Pokémon. It has a small and radish-like body with blue-green leaves and a pink flower bud on its head. Oddish is known for its ability to absorb nutrients from the soil through its roots. It releases a pleasant aroma that attracts other Pokémon. Oddish is a shy and timid Pokémon that prefers to stay hidden during daylight. It is commonly found in shady areas, forests, and gardens.', 50, 45, 55, 75, 65, 30, 5, 'common'),
(44, 'Gloom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png', 'Gloom is the evolved form of Oddish. It has a larger and more droopy appearance with wilting petals on its head. Gloom emits a strong and unpleasant odor that can cause anyone who smells it to feel extremely depressed. However, this foul scent also attracts certain types of Pokémon. Gloom is known to release thick pollen clouds that induce drowsiness and disorientation in its opponents. It is commonly found in overgrown and lush vegetation.', 65, 60, 70, 85, 75, 40, 3, 'common'),
(45, 'Vileplume', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png', 'Vileplume is the evolved form of Gloom. It has a large and vibrant flower on its head that emits a sweet and intoxicating aroma. Vileplume uses its captivating scent to attract pollinating insects and Pokémon. It is believed that the pollen from its flower has healing properties. Vileplume is known for its graceful movements and elegant appearance. It is commonly found in meadows, gardens, and areas abundant with flowers.', 80, 75, 85, 110, 90, 50, 5, 'common'),
(46, 'Paras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png', 'Paras is a bug and grass type Pokémon. It has a small and mushroom-like body with insectoid features. Paras is often seen carrying a parasitic mushroom on its back. The mushroom grows by drawing nutrients from the bug Pokémon\'s body. Despite the symbiotic relationship, Paras seems unbothered by the presence of the mushroom. It is a timid and cautious Pokémon that prefers to stay hidden in moist and dark places.', 70, 35, 55, 45, 55, 25, 1, 'common'),
(47, 'Parasect', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png', 'Parasect is the evolved form of Paras. It has a larger and more developed mushroom on its back, which has taken over its body. Parasect has lost its individuality and is completely controlled by the mushroom. The mushroom releases spores that have mind-controlling properties, allowing it to manipulate Parasect\'s movements. Parasect is often found in dense forests, where it roams around in search of new hosts for its mushroom.', 95, 60, 80, 60, 80, 30, 4, 'rare'),
(48, 'Venonat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png', 'Venonat is a bug and poison type Pokémon. It has a small and fuzzy body covered in purple fur. Venonat has large, red compound eyes that can see in almost complete darkness. It is attracted to bright lights and is often found near streetlights at night. Venonat releases a sweet and sticky fluid from its eyes to immobilize its prey. Despite its somewhat creepy appearance, Venonat is a gentle and docile Pokémon.', 55, 60, 50, 40, 55, 45, 1, 'common'),
(49, 'Venomoth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png', 'Venomoth is the evolved form of Venonat. It has a larger and more menacing appearance with outstretched wings and long antennae. Venomoth is known for its powdery scales that it releases from its wings. The scales have a hypnotic effect, causing drowsiness and confusion in its opponents. Venomoth is a nocturnal Pokémon that is active during the night. It is commonly found in forested areas and marshlands.', 65, 70, 60, 90, 75, 90, 3, 'rare'),
(50, 'Diglett', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png', 'Diglett is a ground type Pokémon that lives underground. Only its head pokes out of the ground, which is often mistaken for a mole or a mole-like creature. Diglett is highly sensitive to vibrations and can sense the movements of its prey from deep underground. It is known for its digging prowess and can tunnel through the earth at impressive speeds. Diglett is commonly found in areas with soft soil or sand.', 55, 10, 25, 35, 45, 95, 2, 'common'),
(51, 'Dugtrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png', 'Dugtrio is the evolved form of Diglett. It is a ground type Pokémon that consists of three Diglett joined together. Each Diglett has its own brain, and they work together to tunnel through the ground. Dugtrio is known for its speed and ability to create tunnels with incredible precision. It can quickly ambush its prey from below the surface. Dugtrio is commonly found in arid environments and deserts.', 100, 35, 50, 50, 70, 120, 3, 'rare'),
(52, 'Meowth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', 'Meowth is a normal type Pokémon. It has a small and cat-like body covered in cream-colored fur. Meowth is known for its fascination with shiny objects, and it has a habit of collecting valuable items. It has sharp claws that it uses for scratching and attacking its opponents. Meowth is a mischievous and cunning Pokémon that is often found in urban areas and near human settlements.', 45, 40, 35, 40, 40, 90, 2, 'common'),
(53, 'Persian', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 'Persian is the evolved form of Meowth. It has a sleek and elegant appearance with a long, graceful tail. Persian is known for its agility and gracefulness. It can move silently and with great precision, making it an excellent hunter. Persian has sharp claws that it uses to slash its opponents. Despite its refined appearance, Persian has a fierce and independent personality. It is commonly found in luxurious and extravagant environments.', 70, 65, 60, 65, 65, 115, 4, 'rare'),
(54, 'Psyduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png', 'Psyduck is a water type Pokémon. It has a small and duck-like body with yellow fur. Psyduck is constantly plagued by a headache, which intensifies when its psychic powers are about to manifest. It often holds its head in its hands to alleviate the pain. Psyduck\'s psychic powers can be unpredictable, and when its headache becomes too severe, it releases a powerful burst of psychic energy. Psyduck is commonly found near bodies of water.', 52, 50, 48, 65, 50, 55, 1, 'common'),
(55, 'Golduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png', 'Golduck is the evolved form of Psyduck. It has a more streamlined and muscular body built for swimming. Golduck is an excellent swimmer and is capable of diving to great depths. It can move through the water with impressive speed and agility. Golduck\'s webbed feet and hands make it a proficient swimmer and allow it to catch prey effortlessly. It is commonly found in lakes, rivers, and other bodies of water.', 82, 80, 78, 95, 80, 85, 3, 'rare'),
(56, 'Mankey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png', 'Mankey is a fighting type Pokémon. It has a small and monkey-like body with a fiery temperament. Mankey is known for its short temper and aggressive nature. It becomes easily enraged and will fiercely attack anything that provokes it. Mankey\'s punches are extremely powerful, and it can deliver multiple strikes in rapid succession. Mankey is commonly found in mountainous areas and forests.', 80, 40, 35, 35, 45, 70, 1, 'common'),
(57, 'Primeape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png', 'Primeape is the evolved form of Mankey. It is a strong and belligerent Pokémon that is always ready for a fight. Primeape is highly territorial and fiercely protective of its territory. It will aggressively attack any intruders that cross its path. Primeape\'s punches are incredibly powerful, and it has a reputation for being one of the strongest fighters among Pokémon. Primeape is commonly found in rugged and challenging environments.', 105, 65, 60, 60, 70, 95, 4, 'rare'),
(58, 'Growlithe', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png', 'Growlithe is a fire type Pokémon that resembles a small and puppy-like creature. It has a thick, orange fur coat and a fluffy tail. Growlithe is known for its loyalty and protective nature. It forms strong bonds with its trainers and will bravely defend them from any danger. Growlithe has an acute sense of smell and can detect the scent of approaching enemies. It is commonly found in grassy fields and near active volcanoes.', 70, 55, 45, 70, 50, 60, 2, 'common'),
(59, 'Arcanine', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png', 'Arcanine is the evolved form of Growlithe. It is a majestic and legendary Pokémon that embodies the qualities of courage and nobility. Arcanine has a regal appearance with a majestic mane and fiery fur. It can run at incredible speeds and is known as the Legendary Pokémon of Fire. Arcanine is revered and respected for its strength, loyalty, and protective nature. It is commonly seen as a symbol of power and authority.', 110, 90, 80, 100, 80, 95, 5, 'rare'),
(60, 'Poliwag', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png', 'Poliwag is a water type Pokémon that resembles a small, blue tadpole. It has a unique spiral pattern on its belly that becomes more pronounced as it evolves. Poliwag is a weak swimmer and often gets swept away by even the slightest currents. It uses its large eyes to detect the flow of water and to find its way back to its group. Poliwag is commonly found near bodies of water, such as ponds and lakes.', 50, 40, 40, 40, 40, 90, 1, 'common'),
(61, 'Poliwhirl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png', 'Poliwhirl is the evolved form of Poliwag. It has a larger and more developed body with stronger muscles. Poliwhirl is capable of living both in water and on land, allowing it to explore various environments. It can use its webbed hands and feet to swim gracefully or traverse across muddy terrains. Poliwhirl has a playful and mischievous nature and often engages in friendly competitions with other Pokémon. It is commonly found near freshwater sources.', 65, 65, 65, 50, 50, 90, 2, 'rare'),
(62, 'Poliwrath', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png', 'Poliwrath is the evolved form of Poliwhirl. It is a powerful water and fighting type Pokémon. Poliwrath has muscular arms and legs that allow it to deliver powerful punches and kicks. It is a skilled swimmer and can swim through rough waters with ease. Poliwrath is known for its calm and composed demeanor, but it becomes fiercely competitive in battle. It is commonly found near bodies of water, such as lakes and rivers.', 95, 90, 95, 70, 90, 70, 3, 'epic'),
(63, 'Abra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', 'Abra is a psychic type Pokémon. It has a small and humanoid-like body with yellow fur. Abra is known for its psychic powers and is capable of teleportation. It can instantly disappear from sight when it senses danger. Abra spends most of its time sleeping and has a deep connection to dreams. It is commonly found in grassy fields and forests.', 20, 25, 15, 105, 55, 90, 4, 'common'),
(64, 'Kadabra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png', 'Kadabra is the evolved form of Abra. It has a more developed and humanoid-like appearance. Kadabra has highly developed psychic abilities and can bend spoons with its mind. It is highly intelligent and is known to possess an IQ that exceeds 5,000. Kadabra\'s psychic powers are so strong that it can create illusions to confuse its opponents. It is commonly found in urban areas and near ancient ruins.', 35, 40, 30, 120, 70, 105, 2, 'rare'),
(65, 'Alakazam', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', 'Alakazam is the final evolved form of Abra. It has a sleek and humanoid-like body with a prominent mustache. Alakazam possesses immense psychic powers and has an IQ that exceeds 5,000. It has a photographic memory and can instantly memorize and calculate complex equations. Alakazam\'s psychic abilities are so powerful that it can bend spoons telekinetically without even touching them. It is commonly found in areas with high psychic energy.', 50, 55, 45, 135, 95, 120, 3, 'epic'),
(66, 'Machop', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', 'Machop is a fighting type Pokémon. It has a muscular and humanoid-like body with bluish-gray skin. Machop trains diligently to build up its muscles and become stronger. It often flexes its muscles to show off its strength. Machop has incredible power and can easily lift and throw objects that are several times its own weight. It has a courageous and determined personality. Machop is commonly found in mountainous areas and training gyms.', 80, 70, 50, 35, 35, 35, 1, 'common'),
(67, 'Machoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png', 'Machoke is the evolved form of Machop. It has an even more muscular and imposing physique. Machoke\'s muscles are so strong that it can move mountains with ease. It is known for its incredible endurance and resilience. Machoke trains rigorously to improve its strength and is often seen engaging in intense physical training. It has a disciplined and hardworking nature. Machoke is commonly found in areas where there are challenging physical tasks.', 100, 80, 70, 50, 60, 45, 5, 'rare'),
(68, 'Machamp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', 'Machamp is the final evolved form of Machop. It is a formidable and powerful Pokémon with a heavily muscled body. Machamp has incredible strength and can throw punches with devastating force. It is capable of moving mountains and is considered one of the strongest fighters among Pokémon. Machamp\'s four arms allow it to deliver multiple strikes simultaneously. It has a competitive and determined personality. Machamp is commonly found in training dojos and battle arenas.', 130, 90, 80, 65, 85, 55, 4, 'epic'),
(69, 'Bellsprout', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png', 'Bellsprout is a grass and poison type Pokémon. It has a plant-like appearance with a long stem and two leaves on top. Bellsprout has a carnivorous nature and uses its mouth-like appendage to capture and consume small insects. It is highly adaptive and can thrive in various environments. Bellsprout uses its roots to absorb nutrients from the soil. It is commonly found in grassy areas and forests.', 75, 50, 35, 70, 30, 40, 1, 'common'),
(70, 'Weepinbell', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png', 'Weepinbell is the evolved form of Bellsprout. It has a bell-shaped body with a gaping mouth and sharp teeth. Weepinbell uses its mouth to secrete a sweet-smelling nectar that attracts prey. Once the prey is near, Weepinbell snaps shut its mouth to ensnare and consume its meal. It is a patient hunter and waits for the perfect moment to strike. Weepinbell is commonly found in areas with rich soil and abundant sunlight.', 90, 65, 50, 85, 45, 55, 2, 'rare'),
(71, 'Victreebel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png', 'Victreebel is the final evolved form of Bellsprout. It has a large and menacing appearance with a bell-shaped body and long vines. Victreebel is a carnivorous Pokémon that uses its vines to ensnare and trap prey. It then digests the trapped prey using powerful acids in its bell-shaped body. Victreebel is highly territorial and will fiercely defend its hunting grounds. It is commonly found in dense forests and swamps.', 105, 80, 65, 100, 70, 70, 3, 'epic'),
(72, 'Tentacool', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png', 'Tentacool is a water and poison type Pokémon. It has a jellyfish-like body with tentacles hanging down. Tentacool has stinging tentacles that it uses to capture and immobilize its prey. It can also release toxic spikes to defend itself from predators. Tentacool is capable of surviving in a wide range of ocean depths and can adapt to various water conditions. It is commonly found in coastal areas and open seas.', 40, 40, 35, 50, 100, 70, 1, 'common'),
(73, 'Tentacruel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png', 'Tentacruel is the evolved form of Tentacool. It has a larger and more menacing appearance with multiple long tentacles. Tentacruel has powerful toxins in its tentacles and can paralyze or kill its prey. It is capable of swimming at high speeds and can even glide above the water surface. Tentacruel is highly territorial and will aggressively defend its territory. It is commonly found in deep ocean waters and coral reefs.', 70, 80, 65, 80, 120, 100, 2, 'common'),
(74, 'Geodude', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', 'Geodude is a rock and ground type Pokémon. It has a rocky, boulder-like body with muscular arms. Geodude can roll itself into a ball and tumble down mountains to move around. It has a sturdy and durable body that can withstand powerful physical attacks. Geodude generates electricity while it moves and can deliver electrically charged punches. It is commonly found in rocky terrains, caves, and mountains.', 80, 40, 100, 30, 30, 20, 1, 'common'),
(75, 'Graveler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png', 'Graveler is the evolved form of Geodude. It has a larger and more rugged appearance with multiple rocky protrusions. Graveler has immense strength and can lift and carry heavy boulders with ease. It often travels in groups and uses its powerful arms to create pathways through rocky terrains. Graveler is known to cause landslides with its movements. It is commonly found in mountainous regions and rocky landscapes.', 95, 55, 115, 45, 45, 35, 2, 'rare'),
(76, 'Golem', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png', 'Golem is the final evolved form of Geodude. It has a massive and boulder-like body with a rugged exterior. Golem is incredibly strong and can effortlessly pulverize large rocks with a single punch. Its body is highly resistant to physical damage. Golem can roll down mountains at high speeds, causing massive destruction in its wake. It is commonly found in volcanic areas and rocky mountain ranges.', 120, 80, 130, 55, 65, 45, 3, 'epic'),
(77, 'Ponyta', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png', 'Ponyta is a fire type Pokémon. It has a small and elegant body with long, flowing flames for a mane and tail. Ponyta\'s flames burn brighter and stronger when it is healthy and full of energy. It can run at incredible speeds, leaving behind a trail of flames. Ponyta is known for its graceful movements and is often admired for its beauty. It is commonly found in grasslands and open fields.', 85, 50, 55, 65, 65, 90, 1, 'common'),
(78, 'Rapidash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png', 'Rapidash is the evolved form of Ponyta. It has a majestic and fiery appearance with a long flowing mane and blazing hooves. Rapidash is incredibly fast and can outrun even the strongest winds. Its flames burn intensely and create a mesmerizing spectacle. Rapidash is known for its loyal and noble nature. It is commonly found in grasslands and open plains.', 100, 65, 70, 80, 80, 105, 5, 'rare'),
(79, 'Slowpoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png', 'Slowpoke is a water and psychic type Pokémon. It has a plump and dazed appearance with a vacant expression. Slowpoke has a very slow and relaxed demeanor. It spends most of its time lazing around and daydreaming. Slowpoke\'s tail contains sweet juices that are highly sought after by other Pokémon. It is commonly found near bodies of water and in lakes.', 65, 90, 65, 40, 40, 15, 4, 'common'),
(80, 'Slowbro', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png', 'Slowbro is the evolved form of Slowpoke. It has a more composed and focused appearance. Slowbro\'s tail is often mistaken for a Shellder, a small clam-like Pokémon that bites onto Slowbro\'s tail. The bite causes Slowbro to undergo a mysterious evolution, resulting in a symbiotic relationship. Slowbro gains enhanced psychic abilities and becomes more formidable in battle. It is commonly found near bodies of water and in coastal areas.', 75, 95, 110, 100, 80, 30, 2, 'rare'),
(81, 'Magnemite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png', 'Magnemite is an electric and steel type Pokémon. It has a metallic, horseshoe-shaped body with magnets on each side. Magnemite can generate electromagnetic waves that disrupt electronic devices. It is often found near power plants and electrical equipment. Magnemite uses its magnetic powers to levitate and move through the air. It can join together with other Magnemite to form a larger cluster. It is commonly found in urban areas and near electrical power sources.', 35, 25, 70, 95, 55, 45, 1, 'common'),
(82, 'Magneton', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png', 'Magneton is the evolved form of Magnemite. It has three Magnemite joined together to form a triangular shape. Magneton generates strong electromagnetic waves that interfere with radio signals and cause disruptions in electronic devices. It can hover in the air using its magnetic powers. Magneton is often seen near power plants and in areas with strong magnetic fields. It is commonly found in urban areas and industrial zones.', 60, 50, 95, 120, 70, 70, 5, 'rare'),
(83, 'Farfetch\'d', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png', 'Farfetch\'d is a normal and flying type Pokémon. It has a distinctive appearance with a leek stalk held in its wings. Farfetch\'d is skilled in using its leek as a weapon in battle. It is known for its honorable nature and strict code of conduct. Farfetch\'d is a rare sight in the wild and is often found in grassy fields and meadows.', 90, 52, 55, 58, 62, 60, 4, 'common'),
(84, 'Doduo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png', 'Doduo is a normal and flying type Pokémon. It has a two-headed bird-like appearance with long legs. Doduo is incredibly fast and can run at high speeds. Each head of Doduo has its own brain, allowing it to perform multiple tasks simultaneously. Doduo is often seen in open grasslands and plains, running and grazing on berries and seeds.', 85, 35, 45, 35, 35, 75, 2, 'common'),
(85, 'Dodrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png', 'Dodrio is the evolved form of Doduo. It has three heads and a more imposing and muscular body. Dodrio is known for its speed and agility, being capable of running at incredible speeds. Each head of Dodrio has its own unique personality and reacts independently to its surroundings. Dodrio is commonly found in open grasslands and wide plains.', 110, 60, 70, 60, 60, 110, 3, 'rare'),
(86, 'Seel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png', 'Seel is a water type Pokémon. It has a sleek and seal-like body with a fluffy white coat. Seel is highly adapted to living in cold environments and is often found in icy waters. It can swim gracefully and dive to great depths. Seel uses its sharp claws to break through ice and catch its prey. It is known for its playful and friendly nature.', 45, 65, 55, 45, 70, 45, 1, 'common'),
(87, 'Dewgong', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png', 'Dewgong is the evolved form of Seel. It has a larger and more elegant body with a long flowing tail. Dewgong is highly adapted to living in cold seas and icy waters. It has excellent swimming and diving abilities and can withstand freezing temperatures. Dewgong uses its streamlined body to glide through the water effortlessly. It is commonly found in arctic regions and in oceans with floating ice.', 70, 90, 80, 70, 95, 70, 5, 'rare'),
(88, 'Grimer', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 'Grimer is a poison type Pokémon. It has a sludge-like appearance with a grimy and sticky body. Grimer is made up of toxic substances and emits a foul odor. It thrives in polluted areas and is often found near factories and waste disposal sites. Grimer can dissolve and consume almost anything, including garbage and waste materials.', 80, 80, 50, 40, 50, 25, 1, 'common'),
(89, 'Muk', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png', 'Muk is the evolved form of Grimer. It has a larger and more menacing appearance with an amorphous body made of toxic sludge. Muk\'s body is highly poisonous and can cause severe contamination. It leaves behind a trail of toxic sludge wherever it moves. Muk is often found in areas with high pollution levels, such as industrial zones and toxic waste dumps.', 105, 105, 75, 65, 100, 50, 5, 'rare'),
(90, 'Shellder', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png', 'Shellder is a water type Pokémon. It has a clam-like appearance with a blue shell. Shellder attaches itself to rocks or other Pokémon using its powerful grip. It feeds on nutrients from its host and grows stronger. Shellder can shoot out powerful jets of water from its shell. It is commonly found in seas and oceans, latching onto slow-moving prey.', 65, 30, 100, 45, 25, 40, 1, 'common'),
(91, 'Cloyster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png', 'Cloyster is the evolved form of Shellder. It has a bivalve shell with sharp spikes and a dark purple coloration. Cloyster is known for its extremely hard and durable shell, which protects it from attacks. It is highly skilled in defensive maneuvers and can close its shell tightly to withstand even powerful strikes. Cloyster is often found in deep seas and rocky coastlines.', 95, 50, 180, 85, 45, 70, 5, 'rare');
INSERT INTO `pokemons` (`id`, `name`, `image`, `description`, `atk`, `hp`, `def`, `sp_atk`, `sp_def`, `spd`, `location`, `rarity`) VALUES
(92, 'Gastly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', 'Gastly is a ghost and poison type Pokémon. It has a gaseous and ethereal appearance, resembling a purple orb with eyes. Gastly is primarily composed of toxic gases and can float through walls and objects. It can emit a hypnotic gas that induces sleep in its opponents. Gastly is often found in abandoned buildings, graveyards, and other spooky locations.', 35, 30, 30, 100, 35, 80, 1, 'common'),
(93, 'Haunter', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png', 'Haunter is the evolved form of Gastly. It has a shadowy and sinister appearance, resembling a floating purple ghost. Haunter is mischievous and enjoys playing pranks on unsuspecting victims. It can phase through solid objects and is known for its ability to lick its opponents, causing a chilling sensation. Haunter is commonly found in dark caves and haunted locations.', 50, 45, 45, 115, 55, 95, 2, 'common'),
(94, 'Gengar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'Gengar is the final evolved form of Gastly. It has a menacing and eerie appearance, resembling a shadowy figure with red eyes. Gengar is a powerful ghost and poison type Pokémon known for its mischievous nature. It enjoys causing fright and confusion among its opponents. Gengar can manipulate shadows and has the ability to curse its foes. It is often found in dark alleys and haunted houses.', 65, 60, 60, 130, 75, 110, 3, 'rare'),
(95, 'Onix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png', 'Onix is a rock and ground type Pokémon. It has a massive and serpentine body made of rocky segments. Onix burrows underground and moves effortlessly through the soil. It can grow up to 28 feet in length. Onix is known for its incredible strength and durability. It is often found in caves, mountains, and rocky terrains.', 45, 35, 160, 30, 45, 70, 4, 'common'),
(96, 'Drowzee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png', 'Drowzee is a psychic type Pokémon. It has a humanoid appearance with a yellow body and a trunk-like snout. Drowzee has the ability to put its opponents to sleep using its hypnotic powers. It can also sense the dreams of others and feed on their dream energy. Drowzee is often found near places where people sleep, such as forests and urban areas.', 48, 60, 45, 43, 90, 42, 5, 'common'),
(97, 'Hypno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png', 'Hypno is the evolved form of Drowzee. It has a more menacing and mysterious appearance, resembling a humanoid creature with a pendulum-like appendage. Hypno is known for its powerful psychic abilities. It can hypnotize and control the minds of its opponents, bending them to its will. Hypno is often found in abandoned buildings and areas with high psychic energy.', 73, 85, 70, 73, 115, 67, 3, 'rare'),
(98, 'Krabby', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 'Krabby is a water type Pokémon. It has a crab-like appearance with a tough exoskeleton and large pincers. Krabby is known for its strong claws, which it uses to grip onto rocks and attack its foes. It is a feisty Pokémon and fiercely defends its territory. Krabby can be found in coastal areas, particularly in sandy beaches and rocky shores.', 105, 30, 90, 25, 25, 55, 1, 'common'),
(99, 'Kingler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png', 'Kingler is the evolved form of Krabby. It has a larger and more powerful build, with a massive claw on one of its pincers. Kingler is highly territorial and known for its aggressive nature. It can deliver devastating claw strikes and crush objects with its powerful grip. Kingler is often found near bodies of water, such as rivers and oceans.', 130, 55, 115, 50, 50, 75, 2, 'rare'),
(100, 'Voltorb', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png', 'Voltorb is an electric type Pokémon. It has a spherical shape and resembles a red and white Poké Ball. Voltorb is known for its explosive nature. It has the ability to self-destruct and release a powerful electric blast. Voltorb often disguises itself among real Poké Balls, making it difficult to distinguish between them. It is commonly found in power plants and areas with high electrical energy.', 30, 40, 50, 55, 55, 100, 4, 'common'),
(101, 'Electrode', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png', 'Electrode is the evolved form of Voltorb. It retains the spherical shape and red and white coloration of its pre-evolution. Electrode is highly energetic and constantly in a state of electrical charge. It can discharge electricity from its body and move at incredible speeds. Electrode is known for its explosive power and can self-destruct to cause massive damage. It is often found in power plants and areas with high electrical activity.', 50, 60, 70, 80, 80, 150, 5, 'rare'),
(102, 'Exeggcute', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png', 'Exeggcute is a grass and psychic type Pokémon. It has an unusual appearance, resembling a cluster of six eggs with faces. Exeggcute is known for its strong telepathic abilities, allowing it to communicate with others of its kind. It often gathers in groups and shares nutrients among its members. Exeggcute is commonly found in forests and areas with rich soil.', 40, 60, 80, 60, 45, 40, 1, 'common'),
(103, 'Exeggutor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png', 'Exeggutor is the evolved form of Exeggcute. It has a tall and imposing appearance, with a long neck and three heads. Exeggutor is known for its immense height, reaching up to 30 feet. Each head has its own personality and can think independently. Exeggutor uses its psychic powers to control the movement of its heads. It is often found in tropical and sunny regions.', 95, 95, 85, 125, 65, 55, 2, 'rare'),
(104, 'Cubone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png', 'Cubone is a ground type Pokémon. It has a small, skull-like mask on its face and carries a bone as a weapon. Cubone is known for its melancholic nature, often seen mourning the loss of its deceased mother. It is a solitary Pokémon that wanders in search of a new family. Cubone can be found in rocky areas and caves.', 50, 50, 95, 40, 50, 35, 4, 'common'),
(105, 'Marowak', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png', 'Marowak is the evolved form of Cubone. It has a larger and more menacing appearance, with a skull helmet and a longer bone weapon. Marowak is a fierce and protective Pokémon that will do anything to defend its territory and loved ones. It wields its bone club with great skill and can deliver powerful strikes. Marowak is often found in graveyards and sacred burial grounds.', 80, 60, 110, 50, 80, 45, 2, 'rare'),
(106, 'Hitmonlee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png', 'Hitmonlee is a fighting type Pokémon. It has a humanoid appearance with long legs and no arms. Hitmonlee is a master of martial arts and specializes in powerful kicks. It can deliver lightning-fast kicks with incredible precision and accuracy. Hitmonlee is highly disciplined and constantly hones its skills through rigorous training. It is often found in dojos and training facilities.', 120, 50, 53, 35, 110, 87, 1, 'rare'),
(107, 'Hitmonchan', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png', 'Hitmonchan is a fighting type Pokémon. It has a humanoid appearance and wears boxing gloves. Hitmonchan is known for its excellent punching techniques and quick reflexes. It can throw a barrage of punches in rapid succession, with each punch having different elemental properties. Hitmonchan is often seen training in gyms and honing its boxing skills. It is a popular choice among trainers who value speed and technique.', 105, 50, 79, 35, 110, 76, 5, 'rare'),
(108, 'Lickitung', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png', 'Lickitung is a normal type Pokémon. It has a long, lickable tongue and a round body. Lickitung is known for its insatiable appetite and its ability to lick anything it comes across. Its tongue is so sticky that it can grip objects and even other Pokémon. Lickitung is often found in grassy areas and forests, where it can find plenty of delicious food to satisfy its never-ending hunger.', 55, 90, 75, 60, 75, 30, 1, 'common'),
(109, 'Koffing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 'Koffing is a poison type Pokémon. It has a round body filled with toxic gases. Koffing constantly releases noxious fumes from the vents on its body. The gases emitted by Koffing can be extremely harmful, causing coughing and choking to those nearby. Koffing is often found in polluted areas and industrial zones, thriving in environments with high levels of toxins.', 65, 40, 95, 60, 45, 35, 2, 'common'),
(110, 'Weezing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png', 'Weezing is the evolved form of Koffing. It has two heads connected by a thin tube. Weezing continues to release toxic gases, but in greater quantities and with more potency than its pre-evolution. The gases emitted by Weezing can be hazardous to both humans and other Pokémon. Weezing is often found in polluted cities and industrial areas, where it thrives in environments filled with toxic fumes.', 90, 65, 120, 85, 70, 60, 4, 'rare'),
(111, 'Rhyhorn', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png', 'Rhyhorn is a ground and rock type Pokémon. It has a tough, armored body and a horn on its forehead. Rhyhorn is known for its immense physical strength and endurance. It can charge at high speeds and deliver devastating horn attacks. Rhyhorn is often used for heavy labor and transportation due to its ability to carry heavy loads. It is commonly found in rocky terrains and mountainous areas.', 85, 80, 95, 30, 30, 25, 2, 'common'),
(112, 'Rhydon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png', 'Rhydon is the evolved form of Rhyhorn. It has an even more formidable appearance, with larger horns and increased muscle mass. Rhydon is known as the Drill Pokémon for its ability to create tunnels by smashing through solid rock with its horn. Rhydon possesses incredible physical strength and can withstand powerful attacks. It is often used in construction and excavation projects. Rhydon can be found in rugged terrains and rocky areas.', 130, 105, 120, 45, 45, 40, 1, 'rare'),
(113, 'Chansey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png', 'Chansey is a normal type Pokémon. It has a round, egg-shaped body and a small pouch on its belly. Chansey is known for its kind and nurturing nature, often caring for injured or sick Pokémon. It has the ability to produce nutritious eggs that are highly sought after for their healing properties. Chansey is commonly found in areas with abundant vegetation and can often be seen working at Pokémon Centers.', 5, 250, 5, 35, 105, 50, 5, 'rare'),
(114, 'Tangela', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png', 'Tangela is a grass type Pokémon. It has a mass of blue vines that cover its round body. Tangela\'s vines are incredibly flexible and can be used to capture and immobilize its prey. It is a shy and elusive Pokémon that often hides among dense vegetation. Tangela\'s vines grow longer and thicker as it ages, granting it increased strength and maneuverability. It is commonly found in forests and grassy meadows.', 55, 65, 115, 100, 40, 60, 1, 'rare'),
(115, 'Kangaskhan', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png', 'Kangaskhan is a normal type Pokémon. It has a large, kangaroo-like body and a baby Pokémon called a Joey that resides in its pouch. Kangaskhan is fiercely protective of its young and will unleash a flurry of powerful attacks to defend them. It possesses incredible strength and can deliver devastating punches and kicks. Kangaskhan is often found in grassy plains and savannahs, where it can graze and care for its young.', 95, 105, 80, 40, 80, 90, 3, 'rare'),
(116, 'Horsea', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png', 'Horsea is a water type Pokémon. It has a small, seahorse-like body and a long snout. Horsea is capable of changing its body color to blend in with its surroundings. It propels itself through water using its tiny fins. Horsea has the ability to shoot powerful jets of water from its mouth, which it uses for defense and capturing prey. It can often be found in oceans and coral reefs.', 40, 30, 70, 70, 25, 60, 4, 'common'),
(117, 'Seadra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png', 'Seadra is the evolved form of Horsea. It has a more elongated body and larger fins. Seadra is a swift swimmer and can maneuver through water with great agility. It is known for its venomous spines, which it uses to fend off attackers and paralyze prey. Seadra is often found in deep sea regions and strong ocean currents, where it hunts for small fish and other aquatic creatures.', 65, 55, 95, 95, 45, 85, 5, 'rare'),
(118, 'Goldeen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png', 'Goldeen is a water type Pokémon. It has a sleek, fish-like body and a prominent horn on its forehead. Goldeen is a skilled swimmer and can swiftly navigate through water. It is known for its beautiful and vibrant colors, which can attract both prey and potential mates. Goldeen is often found in freshwater lakes and rivers, where it feeds on small aquatic insects and plants.', 67, 45, 60, 35, 50, 63, 3, 'common'),
(119, 'Seaking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png', 'Seaking is the evolved form of Goldeen. It has a larger and more majestic appearance, with a prominent crest on its head. Seaking is known for its powerful horn, which it uses to assert dominance and battle rivals. It is a strong swimmer and can navigate through both freshwater and saltwater with ease. Seaking is often found in large bodies of water, where it leads a shoal of Goldeen and protects its territory.', 92, 80, 65, 65, 80, 68, 4, 'rare'),
(120, 'Staryu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png', 'Staryu is a water type Pokémon. It has a star-shaped body with multiple appendages called arms. Staryu can regenerate its limbs if they are damaged or severed. It is capable of absorbing sunlight and converting it into energy. Staryu\'s core emits a bright light that can confuse and distract its opponents. Staryu is often found in ocean waters, where it feeds on plankton and small organisms.', 45, 30, 55, 70, 55, 85, 5, 'common'),
(121, 'Starmie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png', 'Starmie is the evolved form of Staryu. It has a central core with multiple appendages resembling arms that can be rearranged as needed. Starmie possesses powerful psychic and water-based attacks. It can emit energy beams from its core and manipulate water currents to its advantage. Starmie is often found in deep ocean waters, where it searches for prey and protects its territory.', 75, 60, 85, 100, 85, 115, 4, 'rare'),
(122, 'Mr. Mime', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png', 'Mr. Mime is a psychic and fairy type Pokémon. It has a humanoid appearance with a pale pink body and a white, clown-like face. Mr. Mime is known for its miming abilities and can create invisible walls and barriers using its psychic powers. It is a skilled performer and often puts on entertaining shows. Mr. Mime is commonly found in urban areas and places where there is a high concentration of human activity.', 45, 40, 65, 100, 120, 90, 5, 'rare'),
(123, 'Scyther', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png', 'Scyther is a bug and flying type Pokémon. It has a slender, green body with sharp, blade-like arms. Scyther is an agile and swift flyer, capable of maneuvering through the air with great precision. It is known for its incredible speed and slashing attacks. Scyther is often found in grassy fields and forests, where it hunts down prey and engages in fierce battles with rival Pokémon.', 110, 70, 80, 55, 80, 105, 3, 'rare'),
(124, 'Jynx', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png', 'Jynx is an ice and psychic type Pokémon. It has a feminine appearance with long, flowing hair and a curvaceous body. Jynx is known for its mesmerizing dance moves, which it uses to put opponents into a trance-like state. It can unleash powerful psychic attacks and create blizzards of freezing ice. Jynx is often found in cold climates and snowy mountains, where it hunts for prey and hones its dancing skills.', 50, 65, 35, 115, 95, 95, 1, 'rare'),
(125, 'Electabuzz', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png', 'Electabuzz is an electric type Pokémon. It has a muscular body and a series of electrical outlets on its hands and tail. Electabuzz can generate and discharge strong electric currents, which it uses for both offense and defense. It is known for its high-speed movements and lightning-fast strikes. Electabuzz is often found near power plants and areas with strong electrical activity.', 83, 65, 57, 95, 85, 105, 3, 'rare'),
(126, 'Magmar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png', 'Magmar is a fire type Pokémon. It has a robust, reptilian body with a flame-like pattern on its head and tail. Magmar can produce intense heat from its body, causing the air around it to shimmer. It can unleash powerful fire attacks and create searing flames to engulf its opponents. Magmar is often found near active volcanoes and hot springs, where it feeds on volcanic ash and molten rocks.', 95, 65, 57, 100, 85, 93, 4, 'epic'),
(127, 'Pinsir', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png', 'Pinsir is a bug type Pokémon. It has a large, pincer-like horns on its head, which it uses for both defense and offense. Pinsir is incredibly strong and can crush rocks and hard objects with ease. It is known for its powerful grip and ability to lift heavy weights. Pinsir is often found in forests and grassy areas, where it searches for tree sap and battles rival Pokémon for territory.', 125, 65, 100, 55, 70, 85, 2, 'epic'),
(128, 'Tauros', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png', 'Tauros is a normal type Pokémon. It has a bull-like appearance with a muscular body and prominent horns. Tauros is incredibly aggressive and known for its fierce charging attacks. It can run at high speeds and possesses incredible stamina. Tauros is often found in open grasslands and plains, where it forms herds and fiercely protects its territory. It is known to have a short temper and can be difficult to tame.', 100, 75, 95, 40, 70, 110, 1, 'epic'),
(129, 'Magikarp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png', 'Magikarp is a water type Pokémon. It is often regarded as one of the weakest and most pathetic Pokémon. Magikarp is primarily known for its ability to splash around aimlessly in water. However, despite its seemingly useless nature, Magikarp has the potential to evolve into the powerful and formidable Gyarados. Magikarp is often found in lakes, rivers, and other bodies of water.', 10, 20, 55, 15, 20, 80, 3, 'common'),
(130, 'Gyarados', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 'Gyarados is a water and flying type Pokémon. It is the evolved form of Magikarp. Gyarados is an immensely powerful and fearsome Pokémon. It has a serpentine body, large wings, and a fierce expression. Gyarados is known for its destructive nature and devastating attacks. It can create massive whirlpools and generate powerful gusts of wind. Gyarados is often found in large bodies of water, where it dominates and terrorizes other Pokémon.', 125, 95, 79, 60, 100, 81, 5, 'epic'),
(131, 'Lapras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png', 'Lapras is a water and ice type Pokémon. It has a large, turtle-like body with a long neck and a distinctive shell pattern on its back. Lapras is known for its gentle nature and serene appearance. It is a skilled swimmer and can navigate through icy waters with ease. Lapras possesses a beautiful singing voice and is said to bring good fortune to those who hear its song. Lapras is often found in the oceans and lakes of colder regions.', 85, 130, 80, 85, 95, 60, 2, 'common'),
(132, 'Ditto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png', 'Ditto is a normal type Pokémon. It has a unique ability to transform into the appearance of any other Pokémon. Ditto is known for its malleable and amorphous body, which allows it to mimic the characteristics and abilities of its opponents. It can perfectly replicate the moves and appearance of other Pokémon. Ditto is often found in urban areas and places where there is a high concentration of Pokémon species.', 48, 48, 48, 48, 48, 48, 3, 'epic'),
(133, 'Eevee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png', 'Eevee is a normal type Pokémon. It is known for its ability to evolve into various different forms depending on certain conditions. Eevee has a cute and fluffy appearance, making it a popular choice among trainers. It is highly adaptable and can thrive in different environments. Eevee is often found in urban areas and places with a high population of trainers. Its evolution possibilities have made it a sought-after Pokémon by trainers who want a versatile team.', 55, 55, 50, 45, 65, 55, 2, 'common'),
(134, 'Vaporeon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png', 'Vaporeon is a water type Pokémon. It is one of the evolved forms of Eevee. Vaporeon has a sleek and elegant appearance with a mermaid-like tail. It has the ability to manipulate water molecules in the air and create small rain clouds. Vaporeon is a strong swimmer and can move effortlessly through water. It is often found near bodies of water such as lakes, rivers, and oceans. Vaporeon is known for its calm and friendly nature.', 65, 130, 60, 110, 95, 65, 4, 'legendary'),
(135, 'Jolteon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png', 'Jolteon is an electric type Pokémon. It is one of the evolved forms of Eevee. Jolteon has a sleek and agile body covered in fur that can generate static electricity. It is incredibly fast and can discharge powerful electric shocks from its fur. Jolteon is often found in areas with high amounts of electrical activity, such as power plants and cities.', 65, 65, 60, 110, 95, 130, 4, 'epic'),
(136, 'Flareon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png', 'Flareon is a fire type Pokémon. It is one of the evolved forms of Eevee. Flareon has a fluffy and fiery mane around its neck, which can ignite into intense flames. It has the ability to produce and control fire, making it a formidable opponent in battle. Flareon is often found in hot and volcanic regions, where it basks in the heat and hunts for prey.', 130, 65, 60, 95, 110, 65, 3, 'epic'),
(137, 'Porygon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png', 'Porygon is a normal type Pokémon. It is known for being the first virtual Pokémon created through computer programming. Porygon has a polygonal body and a unique appearance. It has the ability to move freely within cyberspace and interact with digital environments. Porygon is often found in areas with advanced technology and computer networks.', 60, 65, 70, 85, 75, 40, 5, 'common'),
(138, 'Omanyte', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png', 'Omanyte is a rock and water type Pokémon. It is an ancient Pokémon that existed millions of years ago. Omanyte has a spiral-shaped shell and tentacle-like appendages. It has the ability to regenerate its shell when damaged. Omanyte is often found in ancient seabeds and fossilized remains, where it feeds on plankton and other small organisms.', 40, 35, 100, 90, 55, 35, 2, 'common'),
(139, 'Omastar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png', 'Omastar is a rock and water type Pokémon. It is the evolved form of Omanyte. Omastar has a large, spiral-shaped shell and multiple tentacles. It has the ability to manipulate water currents and create powerful whirlpools. Omastar is known for its intelligence and is believed to have a long lifespan. It is often found in deep seas and underwater caves.', 60, 70, 125, 115, 70, 55, 4, 'epic'),
(140, 'Kabuto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png', 'Kabuto is a rock and water type Pokémon. It is an ancient Pokémon that was resurrected from a fossil. Kabuto has a hard, exoskeleton-like shell and sharp claws. It is an agile swimmer and can move quickly through water. Kabuto is often found in rocky areas and coastal regions, where it hunts for prey and defends its territory.', 80, 30, 90, 55, 45, 55, 5, 'common'),
(141, 'Kabutops', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png', 'Kabutops is a rock and water type Pokémon. It is the evolved form of Kabuto. Kabutops has a streamlined body with sharp blades extending from its arms. It is a swift and agile predator, capable of slicing through prey with its powerful scythes. Kabutops is often found near rivers and ancient ruins, where it hunts for food and protects its territory.', 115, 60, 105, 65, 70, 80, 2, 'epic'),
(142, 'Aerodactyl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png', 'Aerodactyl is a rock and flying type Pokémon. It is an ancient Pokémon that lived in prehistoric times. Aerodactyl has a reptilian appearance with sharp fangs and wings. It is an incredibly fast flyer and can swoop down on its prey with great speed and precision. Aerodactyl is often found in mountainous regions and cliffs, where it roosts and observes its surroundings.', 105, 80, 65, 60, 75, 130, 3, 'common'),
(143, 'Snorlax', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 'Snorlax is a normal type Pokémon. It is known for its massive size and insatiable appetite. Snorlax has a round and chubby body, resembling a sleeping giant. It spends most of its time sleeping and eating, consuming large amounts of food in one sitting. Snorlax is often found in forests and grassy areas, where it can relax and indulge in its favorite pastimes.', 110, 160, 65, 65, 110, 30, 4, 'epic'),
(144, 'Articuno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', 'Articuno is an ice and flying type Pokémon. It is one of the legendary bird Pokémon and is associated with the power of ice and snow. Articuno has a majestic and elegant appearance, with icy wings and a frosty body. It can create blizzards and freeze the air around it. Articuno is often found in cold and snowy regions, where it soars through the sky with grace and beauty.', 85, 90, 100, 95, 125, 85, 3, 'legendary'),
(145, 'Zapdos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', 'Zapdos is an electric and flying type Pokémon. It is one of the legendary bird Pokémon and possesses incredible electrical powers. Zapdos has a sleek and powerful body, with sharp talons and wings crackling with electricity. It can generate thunderstorms and unleash lightning bolts on its opponents. Zapdos is often found in areas with high levels of electrical activity, such as thunderclouds and power plants.', 90, 90, 85, 125, 90, 100, 1, 'legendary'),
(146, 'Moltres', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', 'Moltres is a fire and flying type Pokémon. It is one of the legendary bird Pokémon and embodies the power of flames. Moltres has a majestic and fiery appearance, with blazing wings and a burning tail. It can create intense heat and generate scorching flames. Moltres is often found in volcanic regions and areas with active lava flows.', 100, 90, 90, 125, 85, 90, 5, 'legendary'),
(147, 'Dratini', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png', 'Dratini is a dragon type Pokémon. It is a small and serpentine Pokémon with a gentle disposition. Dratini has a blue body and a long, sleek tail. It is a highly agile swimmer and can navigate through water with ease. Dratini is often found in lakes and rivers, where it peacefully searches for food and enjoys the tranquility of its surroundings.', 64, 41, 45, 50, 50, 50, 4, 'common'),
(148, 'Dragonair', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png', 'Dragonair is a dragon type Pokémon. It is the evolved form of Dratini. Dragonair has a long and graceful body with shimmering scales. It possesses the ability to control the weather and create gentle breezes. Dragonair is often found near bodies of water, where it glides through the air and delights in the beauty of nature.', 84, 61, 65, 70, 70, 70, 3, 'epic'),
(149, 'Dragonite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 'Dragonite is a dragon and flying type Pokémon. It is the final evolved form of Dratini. Dragonite has a massive and powerful body, capable of flying long distances and carrying heavy loads. It can create strong winds with its wings and generate powerful gusts. Dragonite is often found in coastal areas and islands, where it soars through the sky and surveys its territory.', 134, 91, 95, 100, 100, 80, 2, 'epic'),
(150, 'Mewtwo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', 'Mewtwo is a psychic type Pokémon. It is one of the most powerful Pokémon ever created through genetic manipulation. Mewtwo has a humanoid appearance with sleek and powerful muscles. It possesses extraordinary psychic powers and can read minds and manipulate objects with its mind alone. Mewtwo is often found in remote and secluded areas, where it contemplates its existence and seeks answers to life\'s mysteries.', 110, 106, 90, 154, 90, 130, 6, 'mythic'),
(151, 'Mew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 'Mew is a psychic type Pokémon. It is a mythical Pokémon said to possess the DNA of every Pokémon species. Mew has a small and playful appearance, resembling a cat-like creature. It possesses the ability to learn and use any move, making it highly versatile in battles. Mew is an extremely rare Pokémon, and its existence is often shrouded in mystery.', 100, 100, 100, 100, 100, 100, 2, 'legendary');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pokemons`
--
ALTER TABLE `pokemons`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pokemons`
--
ALTER TABLE `pokemons`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=152;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
